package net.limit.cubliminal.init;

import net.minecraft.client.render.animation.Animation;
import net.minecraft.client.render.animation.AnimationKeyframe;
import net.minecraft.client.render.animation.Animator;
import net.minecraft.client.render.animation.PartAnimation;

public class ModAnimations {

    public static final Animation BACTERIA_WALK = Animation.Builder.withLength(0.5f).looping()
		.addPartAnimation("left_leg",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(-10f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_knee",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(13.49f, 21.94f, 5.12f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.125f, Animator.rotate(38.14f, 17.41f, 11.48f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(8.49f, 21.94f, 5.12f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(13.49f, 21.94f, 5.12f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_ankle",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(-5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.16766666f, Animator.rotate(-5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(-5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_foot",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(-7.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.125f, Animator.rotate(-37.51f, 2.41f, -0.65f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.20834334f, Animator.rotate(-31.26f, 1.91f, -0.51f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(-7.51f, 1.61f, -0.43f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.3433333f, Animator.rotate(-15.01f, 1.01f, -0.27f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.4167667f, Animator.rotate(-11.25f, 0.5f, -0.13f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(-7.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("upper_torso",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(5f, 0f, 5f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.125f, Animator.rotate(2.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(5f, 0f, -5f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.375f, Animator.rotate(2.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(5f, 0f, 5f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(-12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(-12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(-12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_leg",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(-10f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(12.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(-10f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_knee",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0.08f, -2.49f, -5.19f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(0.08f, -2.49f, -5.19f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.375f, Animator.rotate(31.77f, -1.23f, -17.04f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(0.08f, -2.49f, -5.19f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_ankle",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(26.79f, -8.75f, -24.1f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(26.79f, -8.75f, -24.1f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_foot",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(-22.43f, 1.2f, 24.89f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.041676664f, Animator.rotate(-18.6f, -0.64f, 21.93f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.125f, Animator.rotate(-24.92f, 0.03f, 29.27f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.25f, Animator.rotate(-28.61f, -0.11f, 34.39f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.3433333f, Animator.rotate(-43.75f, 11.26f, 46.64f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.4583433f, Animator.rotate(-43.75f, 11.26f, 46.64f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(-22.43f, 1.2f, 24.89f),
                                    PartAnimation.Interpolations.LINEAR))).build();
    public static final Animation BACTERIA_IDLE = Animation.Builder.withLength(4f).looping()
		.addPartAnimation("right_arm",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(2f, Animator.rotate(0f, 0f, -1f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(4f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(2f, Animator.rotate(0f, 0f, 1f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(4f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR))).build();
    public static final Animation BACTERIA_ATTACK = Animation.Builder.withLength(0.5f)
		.addPartAnimation("upper_torso",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.041676664f, Animator.rotate(30f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.20834334f, Animator.rotate(32.5f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.4583433f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_arm",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0.041676664f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.125f, Animator.rotate(-59.4f, -10.8f, -6.33f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.2916767f, Animator.rotate(-58.81f, -15.09f, -8.96f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.3433333f, Animator.rotate(-58.81f, -15.09f, -8.96f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("right_hand",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0f, 75f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_arm",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0.041676664f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.125f, Animator.rotate(-62.14f, 8.86f, 4.65f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.2916767f, Animator.rotate(-61.68f, 13.27f, 7.05f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.3433333f, Animator.rotate(-61.68f, 13.27f, 7.05f),
                                    PartAnimation.Interpolations.LINEAR),
                            new AnimationKeyframe(0.5f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_elbow",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0f, 0f, 0f),
                                    PartAnimation.Interpolations.LINEAR)))
		.addPartAnimation("left_hand",
                    new PartAnimation(PartAnimation.AnimationTargets.ROTATE,
                            new AnimationKeyframe(0f, Animator.rotate(0f, -90f, 0f),
                                    PartAnimation.Interpolations.LINEAR))).build();
}
